#####################################################################
# AIRA Private Cellular Radio Access Network (RAN) Configuration
# Proprietary Profile - Adam Eehan (2026)
# Classification: Strictly Closed Source
# FEATURES DEPLOYED: Core PLMN Synchronization & Optimized RF Gain Matrix
# DESIGNED FOR: Offline Educational Node (South Sudan Project) - MADE IN INDIA 🇮🇳
#####################################################################

[enb]
enb_id = 0x19B
mcc = 001                         # db_subscriber-ലെ PLMN ഐഡിയുമായി സിങ്ക് ചെയ്തിരിക്കുന്നു
mnc = 01                          # കോർ നെറ്റ്‌വർക്ക് മാച്ചിങ് കോഡ്
mme_addr = 127.0.0.1
gtp_bind_addr = 127.0.0.1
s1c_bind_addr = 127.0.0.1

[enb_files]
sib_config = sib.conf
rb_config  = rb.conf

[rf]
# Software Defined Radio (SDR) Hardware Parameters
dl_earfcn = 3400                  # LTE Band 7 (Custom Experimental Frequency)
tx_gain = 45                      # കുട്ടികളുടെ ഫോണുകളിലേക്ക് ലോക്കൽ സിഗ്നൽ റേഞ്ച് കൂട്ടാൻ പവർ 45 ആക്കി
rx_gain = 40                      # റിസീവർ സെൻസിറ്റിവിറ്റി കറക്റ്റ് ലെവലിൽ നിലനിർത്തി
device_name = uhd                 # HackRF One / USRP പെരിഫറലുകൾക്കുള്ള സപ്പോർട്ട്
device_args = num_recv_frames=64
